# Generated by Django 2.1.7 on 2019-02-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('itemVoteCount', models.IntegerField()),
                ('centerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project_app.Center')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
