# Generated by Django 2.1.7 on 2019-02-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20190226_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centerlist',
            old_name='userId',
            new_name='centerId',
        ),
    ]
