# Generated by Django 2.1.7 on 2019-02-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20190225_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('itemCount', models.IntegerField()),
                ('centerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='project_app.Center')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='project_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='centerId',
        ),
        migrations.RemoveField(
            model_name='item',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
